### ISSUE TITLE
Ability to choose verify items

### ISSUE THREAD

**Issue by ihipop** [sunjw/fhash#1]
Very awesome tool to replace the `Hash.exe` (by http://keir.net/hash.html) which could not calculate  the hash with SHA256 algorithm
it will more convenience  and save resource  to have the ability to choose which item （**Time/Version/MD5/SHA1/CRC32/ETC.**） to be calculated
just like `Hash.exe` did.
非常赞的工具 代替了keir的hash.exe（不能计算SHA256）
要是能和hash.exe一样选择校验项目（**时间/版本/MD5/SHA1/CRC32/ETC.**）就好了 能节约资源开销
![image](https://cloud.githubusercontent.com/assets/423077/11765564/842cbda2-a198-11e5-98ff-4a714cdb7ee0.png)

**Comment by ihipop** [comment]
另外，http://www.sunjw.us/ 貌似无法评论，那个反垃圾插件有问题

**Comment by sunjw** [comment]
No need, I've tested that just calculates some hash values doesn't make whole progress  obviously faster. The bottleneck is hard disk and my file read code.
没有必要，测试过只计算部分哈希，基本没有能够看到速度提升。瓶颈是磁盘和我的读磁盘方法。
