### ISSUE TITLE
Feature request: Ability to add/remove hashes

### ISSUE THREAD

**Issue by vatterspun** [sunjw/fhash#2]
(This is a low-priority request)

**Current behavior**
The hashes CRC32, MD5, SHA1, and SHA256 are all run on every program added to fhash 

**Requested behavior**
Settings menu of some sort to add or remove hashes

**Why?**
Since hashing speeds up or slows down based on the hashes calculated (and not everyone needs sha256), it might make sense to calc some hashes and not others.  This would help for users calculating large volumes (e.g. CD images).

**Comment by sunjw** [comment]
Actually, hashing speed is based on your disk read speed. Compare to disk read speed, hash calculation is very fast on current CPU. So maybe not calcuating SHA256 would not "help for users calculating large volumes". I think there is not need to add an option for which kinds of hash you want to calcuate. Just click to run and get all results, then you do what you need. This is very easy to use.

**Comment by sunjw** [comment]
By the way, fHash is just read data once from disk for all these hash calculation, it is not like some others which will read data again for a different hash calculation.

**Comment by vatterspun** [comment]
> I think there is not need to add an option for which kinds of hash you want to calcuate

Make sense.  Feel free to close the issue.

> ... it is not like some others which will read data again for a different hash calculation.

Very cool.  I've noticed it quite fast compared to similar tools so I'm not surprised.
