### ISSUE TITLE
VT doesn't support search results on SHA512

### ISSUE THREAD

**Issue by wesinator** [sunjw/fhash#20]
VirusTotal doesn't give results for sha512, so the "Search VirusTotal" option could be disabled on SHA512

I think add an `if` block before https://github.com/sunjw/fhash/blob/56f0986dddde27f494ca293e4b272c18d873ac47/trunk/source/OSXUI/MainViewController.mm#L554 ?

<img width="202" alt="image" src="https://user-images.githubusercontent.com/5124946/221682084-cd0caaa4-de3b-48d1-a236-cfde8f4d26ce.png">

**Comment by sunjw** [comment]
I'll leave this open to see other comments.
