### ISSUE TITLE
几个建议

### ISSUE THREAD

**Issue by snowdream** [sunjw/fhash#21]
我试了一大堆Hash工具，这个fhash是唯一能在WinPe上使用的Hash工具。

👍

几个建议：

1. 多语言
2. windows软件包（静态链接库，非商店打包）
3. 多Hash算法
4. 支持32位（打包）

**Comment by sunjw** [comment]
1. 多语言：本身就已经支持中文和英文
2. windows软件包（静态链接库，非商店打包）：这个 [Release](https://github.com/sunjw/fhash/releases/tag/3.0.1) 中包含非 Store 版 [fHash64-2.4.0-win64.zip](https://github.com/sunjw/fhash/releases/download/3.0.1/fHash64-2.4.0-win64.zip) 下载
3. 多Hash算法：现有的短期内不会再增加
4. 支持32位（打包）：老版本有 32 位支持，可以去 SourceForge.net 的下载里找

**Comment by snowdream** [comment]
为什么最新的版本，win的只能从商店下载？😂

**Comment by sunjw** [comment]
目前 store 上是 UWP 版，独立下载的是 MFC 版。
MFC 版的 explorer 右键菜单是通过注册表添加的，store app 是不允许的，context menu handler 也是 WinAPI 方式的，所以上不了 store，但是 MFC 版可以支持 Windows 7 到之后的版本。
UWP 版使用的组件和一些 API 需要通过 store 安装才能使用（可以开发模式侧加载，但是对很多人不适用），而且只支持 Windows 10 较新版本，所以无法提供下载安装。

**Comment by snowdream** [comment]
好的，谢谢。

那这么说以后的win应用很少能安装在WindowsPE上的啦。
那上面都没有商店。

**Comment by sunjw** [comment]
如果不涉及到右键菜单或者注册表之类的，一般的 app 可以直接在 store 上发布，和普通安装运行没有区别。Store 上的除非是 UWP 或者 Windows App SDK 的，一般也都是可以直接安装运行的。
