### ISSUE TITLE
win10专业版系统显示“拒绝访问”？

### ISSUE THREAD

**Issue by aw59** [sunjw/fhash#23]
![屏幕截图 2023-07-08 124310](https://github.com/sunjw/fhash/assets/70953327/1b38ffd8-3fd0-4f37-848e-c3e9b1f77198)
![屏幕截图 2023-07-08 124323](https://github.com/sunjw/fhash/assets/70953327/a0553d6b-6c48-407f-a06c-1434ec3ba79a)

**Comment by sunjw** [comment]
https://support.microsoft.com/zh-cn/windows/-windows%E8%AE%BF%E9%97%AE%E5%92%8C%E9%9A%90%E7%A7%81-a7d90b20-b252-0e7b-6a29-a3a688e5c7be
