### ISSUE TITLE
Unable to add fHash to Windows Context Menu

### ISSUE THREAD

**Issue by RyanBlakeIT** [sunjw/fhash#24]
After updating to the Windows Store app, I do not see a way to enable the Hash with fHash context menu anymore.  I tried to figure this out on my own but was unsuccessful.  I see it's mentioned in screenshots and I've used it with the thick app before, but don't see how to do it now.

**Comment by sunjw** [comment]
No option to, it is bultin with UWP. Even it is not controlled by fHash app, the app just tell Windows to register an item in context menu, but Windows decides to show it or not. **If it is the first time you installed fHash from Windows Store, you need to logoff then login or just reboot Windows to see the new context menu item.** It is a designed Windows behavior. If you still cannot see fHash item in your context menu like the screenshot after reboot, you need to check your Windows 10/11 settings or group policy.
![screenshot](https://raw.githubusercontent.com/sunjw/fhash/master/assets/win_uwp_context_menu_light_cut.png)

**Comment by RyanBlakeIT** [comment]
Hi @sunjw - My apologies, the issue was that it took a reboot before it showed up in the context menu whereas I'm used to seeing it immediately after installing the old client.  I already use the "Legacy" Context menu still so it wasn't an issue of it hiding.  Thank you very much for your help.  It might be helpful to mention that after installation that the context menu will show up after a reboot?

**Comment by sunjw** [comment]
>  It might be helpful to mention that after installation that the context menu will show up after a reboot?

No really necessary, because it is a strange behavior of Windows 10/11. On some new installed Windows 11, I found the new context menu is shown immediately after installation finished from Microsoft Store. It seems that Microsoft is working on this.
And it is the only one ticket some one mentioned this "issue".
