### ISSUE TITLE
Feature request: Ability to add/remove hashes

### ISSUE THREAD

**Issue by vatterspun** [sunjw/fhash#3]
(This is a low-priority request)

**Current behavior**
Generates a SHA256 hash for files but you have to manually copy this value and paste it into the VirusTotal website interface to get an evaluation (if any) for a given file.

(By way of example, here's the listing on fhash.exe: https://www.virustotal.com/file/e5663cd84da6dcd742f0af0833478bc9ea33f915ae00e70dcacaff5ec52cc1f5/analysis/ )

**Requested behavior**
One of a few possible approaches:
-  If a URL is a ZIP, 7Z, RAR, EXE or other file type that VirusTotal might catalog, a button visible to check a given file hash in VirusTotal database (which is essentially just a url formatted like https://www.virustotal.com/file/<insert hash value>/analysis/ ).  The button could also include the VirusTotal 
-  Optional inclusion of the VirusTotal URL in the output so user can check for themselves

... or something similar.

**Why?**
As VirusTotal is increasingly the most common and useful tool available to average internet users that directly relates to the use of hash values, some kind of integration would benefit fhash's users.  Especially since the tool is already calculating high security SHA256 values.

**Comment by sunjw** [comment]
Good idea, and I'll consider maybe add a link/links on hash result for searching the hash value.

**Comment by vatterspun** [comment]
> ... I'll consider maybe add a link/links on hash result for searching the hash value

Awesome, glad that helped :)

**Comment by sunjw** [comment]
After c197e39ce32014ca2b918b196d1331ac3bacf97d, implemented contextual menu on hash value for Windows

**Comment by sunjw** [comment]
After fd12f85fdb60e33d8ba821ca6271ea4aced33616, implemented contextual menu on hash value for macOS.

**Comment by vatterspun** [comment]
I just went and tested v.2.0.4.0 and there's no virustotal link.  Am I missing something?

**Comment by sunjw** [comment]
@vatterspun No, it is not in 2.0.4. It will be in next release - version 2.1. I'am still testing it. Or if you want to try this feature so hurry, you can compile fHash from code.

**Comment by vatterspun** [comment]
Oh no problem :)  I can wait.

**Comment by smaragdus** [comment]
@vatterspun
Thanks for the nice idea.
@sunjw
Thanks for "Search VirusTotal" implementation, it is very useful.
What about "Stay on Top" option?

**Comment by sunjw** [comment]
@smaragdus Thanks, and I'll consider.
