### ISSUE TITLE
Feature request: support for hashing filetypes

### ISSUE THREAD

**Issue by vatterspun** [sunjw/fhash#4]
**Current behavior**

To verify a .sfv, .crc, .md5, .sha1, a user must open the file in a text editor and do a manual search for a given file/hash.  Additionally, there is no way to generate one of these files with fhash apart from familiarity with the format and manually entering these values (unlikely anyone will do this). 

**Requested behavior**

The ability to save and verify hash values.  Any automation when creating/verifying a hash file would add to the simplicity of the program.

**Possible issues**

I recognize it may be out of scope or impossible to generate or verify thousands of hashes with fHash, which is intended as a fairly simple hashing tool.  Users with these needs will likely seek other programs for advanced verification needs (i.e. what sysadmins would need).

**Comment by sunjw** [comment]
Maybe in this scenario, a shell script would be better solution. Not a GUI tool.
