### ISSUE TITLE
SHA-512

### ISSUE THREAD

**Issue by smaragdus** [sunjw/fhash#5]
I would like to suggest support for SHA-512 which I think will be useful not only for me.

**Comment by sunjw** [comment]
Good suggestion

**Comment by stolle** [comment]
Will this happen anytime soon?

**Comment by sunjw** [comment]
Not soon, but I think this will happen.

**Comment by sunjw** [comment]
Implemented in 2.3.0 and will release soon.

**Comment by smaragdus** [comment]
@sunjw 

I checked versions [2.2.3](https://github.com/sunjw/fhash/releases/tag/2.2.3), [2.2.4](https://github.com/sunjw/fhash/releases/tag/2.2.4), [2.2.5](https://github.com/sunjw/fhash/releases/tag/2.2.5) for Windows, still no trace of SHA-512.

**Comment by sunjw** [comment]
2.3.0 released
https://github.com/sunjw/fhash/releases/tag/2.3.0
