### ISSUE TITLE
Auto clear

### ISSUE THREAD

**Issue by gingerbeardman** [sunjw/fhash#6]
I only want to see hash of the most recent file I dropped, so please add an option to auto clear on each file drop.

thanks!

**Comment by sunjw** [comment]
I'm afraid not. fHash will not have options on UI. I'll keep this issue open, to see if others want this option.

**Comment by gingerbeardman** [comment]
But it already has the UPPERCASE option in the UI?

**Comment by sunjw** [comment]
Yes, but anyway, no more, I hope.  :sweat_smile:

**Comment by gingerbeardman** [comment]
OK. I'll write it myself

**Comment by smaragdus** [comment]
I don't think that "Auto Clear" check-box will add so much clutter to the GUI.
For me "Auto Clear" would be useful since it will spare me an extra click. ;)

**Comment by gingerbeardman** [comment]
Here's my own app, [Hash.app.zip](https://github.com/sunjw/fhash/files/2302036/Hash.app.zip) (version 1.3)

feel free to use it @smaragdus 

<img width="707" alt="screen shot 2018-08-20 at 11 33 15" src="https://user-images.githubusercontent.com/49612/44335633-fc3bc980-a46c-11e8-9e66-58e796d9d6c8.png">

Supports:
- auto clear on each operation
- open with
- select on launch
- drag and drop after window is open
- single or multiple files
- accepts many binary file types
- resizable window
- hold alt to only calculate quickest hashes (CRC32, XHH, MD5)
- full process also includes slower hashes (SHA1, SHA256)

**Comment by smaragdus** [comment]
@gingerbeardman 
You are very kind, thank you very much, but I am Windows-only user. ;)
