### ISSUE TITLE
On Top

### ISSUE THREAD

**Issue by smaragdus** [sunjw/fhash#7]
For me "On Top" check-box will facilitate the usage of **fHash**.

Currently I am using an external tool ([SmartSystemMenu](https://github.com/AlexanderPro/SmartSystemMenu)) to achieve this but I think that native support for "On Top" would be handier.

I have already mentioned this suggestion [here](https://github.com/sunjw/fhash/issues/3#issuecomment-255490158).

**Comment by sunjw** [comment]
Good suggestion, always.

**Comment by sunjw** [comment]
Not going to implement.
