### ISSUE TITLE
请问如何将文件路径通过AppleScript交给fHash啊？

### ISSUE THREAD

**Issue by suliveevil** [sunjw/fhash#9]
希望能通过AppleScript将文件完整路径交给fHash，而不仅仅通过打开app、拖拽文件的形式。

**Comment by sunjw** [comment]
命令行可以调用
open -a fHash.app /path/to/file1 /path/to/file2
applescript 会出现权限问题

**Comment by sunjw** [comment]
applescript 这样可以
do shell script "open -a fHash.app /path/to/file1 /path/to/file2"

**Comment by suliveevil** [comment]
> applescript 这样可以
> do shell script "open -a fHash.app /path/to/file1 /path/to/file2"

我是这样实现的：


```applescript
tell application "System Events"
	tell application "Finder"
		set finderSelection to selection as alias list
	end tell
	if finderSelection ≠ {} then
		-- tell application "fHash"
		tell application id "org.sunjw.fHashMacUI"
			activate
			open finderSelection
		end tell
	end if
end tell
```

**Comment by sunjw** [comment]
OK.
